checks:
    php: true

coding_style:
    php: {  }

filter:
    excluded_paths: ["app/*", "bin/*", "tests/*", "vendor/*", "web/*"]

build:
    dependencies:
        before:
            -
                command: "cp app/config/parameters.yml.dist app/config/parameters.yml"
            -
                command: "composer install --no-progress --no-interaction --no-scripts"
            -
                command: "php bin/console doctrine:database:create --if-not-exists"
            -
                command: "composer install --no-progress --no-interaction"
    environment:
        php:
            version: "7.0.4"
    tests:
        override:
            -
                command: "php bin/phpunit -c phpunit.xml --colors=always --verbose --coverage-clover=coverage.xml"
                coverage:
                    file: "coverage.xml"
                    format: "php-clover"
