version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.2
      - image: circleci/openjdk:8-jdk # ant only
    steps:
      - checkout
#       - run: sudo apt-get install -y ant
      - run: cp app/config/parameters.yml.dist app/config/parameters.yml
      - run: composer install --no-progress --no-interaction
      - run: ant test:with-coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  test-only:
    jobs:
      - test
