battleship.game.api.statistics:
  path:     /statistics
  defaults: { _controller: AppBundle:Statistics:overall }
  methods:  [GET]
#  requirements:
#    _format: json
battleship.game.api.init:
  path:     /init
  defaults: { _controller: AppBundle:Game:init }
  methods:  [POST]
  requirements:
#    _format: json
#    _content: '\"data\"\:[^\,\}]*'
battleship.game.api.turn:
  path:     /turn
  defaults: { _controller: AppBundle:Game:turn }
  methods:  [POST]
#  requirements:
#    _format: json
