worldstores/battleship:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
worldstores/battleship/turn:
    path:     /turn
    defaults: { _controller: AppBundle:Default:turn }
worldstores/battleship/start:
    path:     /start
    defaults: { _controller: AppBundle:Default:start }
worldstores/battleship/finish:
    path:     /finish
    defaults: { _controller: AppBundle:Default:finish }

